/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author sir
 */
import javax.swing.ButtonGroup;
import java.sql.*;

import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
public class eigh extends javax.swing.JFrame {

    /**
     * Creates new form eigh
     */
    public eigh() {
        initComponents();
        groupButton();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(420, 321));
        getContentPane().setLayout(null);

        jRadioButton1.setBackground(new java.awt.Color(0, 0, 0));
        jRadioButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setText("By name");
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(26, 29, 90, 23);

        jRadioButton2.setBackground(new java.awt.Color(0, 0, 0));
        jRadioButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton2.setText("By date (dd/mm/yy)");
        getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(26, 70, 153, 23);

        jRadioButton3.setBackground(new java.awt.Color(0, 0, 0));
        jRadioButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRadioButton3.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton3.setText("By aadhar card");
        getContentPane().add(jRadioButton3);
        jRadioButton3.setBounds(26, 111, 117, 23);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(209, 53, 135, 40);

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(60, 163, 80, 30);

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Submit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(277, 163, 90, 30);

        jLabel1.setToolTipText("");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 410, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
String name=null,dob=null,gender=null,place=null,contact=null,aadhar = null,serial=null,birthmark=null;
if(jRadioButton1.isSelected())
{
    try{
    String s=jTextField1.getText();    
        Class.forName("com.mysql.jdbc.Driver");       
        Connection con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost/crime","root","");
        Statement stmt=con.createStatement();
        String sqq="Select * from missing where name='"+s+"'";
        ResultSet rs=stmt.executeQuery(sqq);
        while(rs.next())
        {
            serial=rs.getString("serial");
        name=rs.getString("name");
        
         
          gender=rs.getString("Gender");
         dob=rs.getString("Dob");
         birthmark=rs.getString("birthmark");
         place=rs.getString("place");
          contact=rs.getString("phone");
          aadhar=rs.getString("aadhar");
        }
        if(s.equalsIgnoreCase(name))
{JOptionPane.showMessageDialog(null,"The record of this missing person is as following:-       \n Serial Number:- "+serial+ " \n Name:- "+name+" \n Gender:- "+gender+" \n Date of Missing:- "+dob+" \n Birthmark:- "+birthmark+" \n Last seen at:- "+place+" \n Contact number:- "+contact+"\n Aadhar card number:- "+aadhar+" ");}
                                           
else{JOptionPane.showMessageDialog(null,"Invalid name entered.");}
    }
    
    catch(Exception cd)
            {System.out.println(cd);
            }
}
else if(jRadioButton2.isSelected())
{try{
    String st=jTextField1.getText();    
        Class.forName("com.mysql.jdbc.Driver");       
        Connection con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost/crime","root","");
        Statement stmt=con.createStatement();
        String sqq="Select * from missing where Dob='"+st+"'";
        ResultSet ras=stmt.executeQuery(sqq);
        while(ras.next())
        {
            serial=ras.getString("serial");
        name=ras.getString("name");
        
         
          gender=ras.getString("Gender");
         dob=ras.getString("Dob");
         birthmark=ras.getString("birthmark");
         place=ras.getString("place");
          contact=ras.getString("phone");
          aadhar=ras.getString("aadhar");
        }
        if(st.equalsIgnoreCase(dob))
{JOptionPane.showMessageDialog(null,"The record of this missing person is as following:-       \n Serial Number:- "+serial+ " \n Name:- "+name+" \n Gender:- "+gender+" \n Date of Missing:- "+dob+" \n Birthmark:- "+birthmark+" \n Last seen at:- "+place+" \n Contact number:- "+contact+"\n Aadhar card number:- "+aadhar+" ");}
                                           
else{JOptionPane.showMessageDialog(null,"Invalid date entered.");}
    }
    
    catch(Exception cde)
            {System.out.println(cde);
            }
}
else if(jRadioButton3.isSelected())
{
    try{
    String as=jTextField1.getText();    
        Class.forName("com.mysql.jdbc.Driver");       
        Connection con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost/crime","root","");
        Statement stmt=con.createStatement();
        String sqq="Select * from missing where aadhar='"+as+"'";
        ResultSet rts=stmt.executeQuery(sqq);
        while(rts.next())
        {
            serial=rts.getString("serial");
        name=rts.getString("name");
        
         
          gender=rts.getString("Gender");
         dob=rts.getString("Dob");
         birthmark=rts.getString("birthmark");
         place=rts.getString("place");
          contact=rts.getString("phone");
          aadhar=rts.getString("aadhar");
        }
        if(as.equalsIgnoreCase(aadhar))
{JOptionPane.showMessageDialog(null,"The record of this missing person is as following:-       \n Serial Number:- "+serial+ " \n Name:- "+name+" \n Gender:- "+gender+" \n Date of Missing:- "+dob+" \n Birthmark:- "+birthmark+" \n Last seen at:- "+place+" \n Contact number:- "+contact+"\n Aadhar card number:- "+aadhar+" ");}
                                           
else{JOptionPane.showMessageDialog(null,"Invalid input.");}
    }
    
    catch(Exception cdd)
            {System.out.println(cdd);
            }
}
else{JOptionPane.showMessageDialog(this, "invalid input.");}
   // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
sixth ss=new sixth();
ss.setVisible(true);
ss.setLocationRelativeTo(null);
setVisible(false);
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public void groupButton(){
        ButtonGroup bg=new ButtonGroup();
        bg.add(jRadioButton1);
        bg.add(jRadioButton2);
        bg.add(jRadioButton3);
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(eigh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(eigh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(eigh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(eigh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new eigh().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
